services:
  redirection:
    image: nginx
    volumes:
      - ./templates:/etc/nginx/templates
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - UFFIZZI_URL=http://localhost/
